source("accessors.r")
second(z)
minute(z)
hour(z)
yday(z)
wday(z)
mday(z)
week(z)
month(z)
year(z)
tz(z)
am(z)
pm(z)
'second<-'(z, 3)
class('second<-'(z, 3))
'minute<-'(z,3)
'hour<-'(z,3)
'yday<-'(z,3)
class('yday<-'(z,3))
'wday<-'(z,3)
'mday<-'(z,3)
'week<-'(z,3)
'month<-'(z,3)
'year<-'(z,3)
update.Date(z, year = 2000, month = 1, mday = 31, hour = 12, minute = 30, second = 30)
class(update.Date(z, year = 2000, month = 1, mday = 31, hour = 12, minute = 30, second = 30))
update.Date(z, year = 2000, month = 1, day = 31)
class(update.Date(z, year = 2000, month = 1, day = 31))
decimal_date(z)
leap.year(z)
#does it have an is.Object identifier?
do.call(paste("is", class(z)[1], sep = "."), list(z))
ymd(z)
floor_date(z, "second")
floor_date(z, "minute")
floor_date(z, "hour")
floor_date(z, "day")
floor_date(z, "week")
floor_date(z, "month")
floor_date(z, "year")
class(floor_date(z, "second"))
class(floor_date(z, "year"))
ceiling_date(z, "second")
ceiling_date(z, "minute")
ceiling_date(z, "hour")
ceiling_date(z, "day")
ceiling_date(z, "week")
ceiling_date(z, "month")
ceiling_date(z, "year")
class(ceiling_date(z, "second"))
round_date(z, "second")
round_date(z, "minute")
round_date(z, "hour")
round_date(z, "day")
round_date(z, "week")
round_date(z, "month")
round_date(z, "year")
class(round_date(z, "second"))
z + years(1)
class(z + years(1))
z - days(1)
class(z - days(1))
class(Sys.time() - z) #should be a duration object
class((z + 3600) - z) #should be a duration object
z - z