// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// C_force_tz
Rcpp::newDatetimeVector C_force_tz(const Rcpp::NumericVector dt, const Rcpp::CharacterVector tz, const bool roll);
RcppExport SEXP lubridate_C_force_tz(SEXP dtSEXP, SEXP tzSEXP, SEXP rollSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector >::type tz(tzSEXP);
    Rcpp::traits::input_parameter< const bool >::type roll(rollSEXP);
    rcpp_result_gen = Rcpp::wrap(C_force_tz(dt, tz, roll));
    return rcpp_result_gen;
END_RCPP
}
