# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_update_dt <- function(dt, year, month, yday, mday, wday, hour, minute, second, tz = NULL, roll = FALSE) {
    .Call('lubridate_C_update_dt', PACKAGE = 'lubridate', dt, year, month, yday, mday, wday, hour, minute, second, tz, roll)
}

C_force_tz <- function(dt, tz, roll = FALSE) {
    .Call('lubridate_C_force_tz', PACKAGE = 'lubridate', dt, tz, roll)
}

